### ISSUE TITLE
[BUG] Does not lint again after reviewers are added.

### ISSUE THREAD

**Issue by schnetzi** [innerspacetrainings/Prace.js#18]
**Describe the bug**
When I open the PR but want to add the reviewers later Prace should lint again after I added the reviewers. Now it does not and I have to push again to get the linting of Prace correct.

**Configuration files**
```yaml
# prace.yml

version: 1
title:
    patterns:
        - '[\w\s]+'
    error: 'The title cannot be empty'
body:
    patterns:
        - '[\w\s]+'
    error: The body cannot be empty
reviewers:
    minimum: 1
```

```yaml
# workflows/prace.yml

name: Prace.js
on:
    pull_request:
        types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            - uses: innerspacetrainings/Prace.js@master
              with:
                  configuration-path: .github/prace.yml
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Expected behaviour**
On a already created PR when I add reviewers Prace should lint again.
